cache:
  directories:
    - $HOME/.composer/cache

language: php

services:
  - docker

env:
  global:
    - DB_DRIVER="mysql"
    - DB_SERVER="localhost"
    - DB_USER="username"
    - DB_PASSWORD="password"
    - DB_DATABASE="scout_testing"
    - SECURITY_KEY="8Nq2DigszBHoASg5ApyLDPeVuuIGwarF"
    - DEFAULT_SITE_URL="https://your-site-url.test/"

matrix:
  include:
    - php: 7.1
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.1
      env: COMPOSER_FLAGS='--prefer-stable'
    - php: 7.2
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.2
      env: COMPOSER_FLAGS='--prefer-stable'
    - php: 7.3
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.3
      env: COMPOSER_FLAGS='--prefer-stable'
    - php: 7.4
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.4
      env: COMPOSER_FLAGS='--prefer-stable'
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot
    
before_install:
  - composer config discard-changes true
  - travis_retry composer self-update

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction --no-suggest

before_script:
  - sudo service mysql stop
  - docker-compose -f ./tests/docker-compose.yml up -d
  - php tests/wait.php
  - touch ./tests/.env

script:
  - vendor/bin/codecept --coverage-text

after_script:
  - docker-compose -f ./tests/docker-compose.yml down